### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Garanas** [FAForever/BlueprintCompiler#1]
@ChrisKitching are you fine with me introducing a MIT license to this repository?

**Comment by ChrisKitching** [comment]
Go for it.

**Comment by ChrisKitching** [comment]
I'm pleasantly surprised to see anyone is using this :D

**Comment by Garanas** [comment]
After investigating we may use the [BrewLan Wiki generator](https://github.com/The-Balthazar/BrewWikiGen) instead. It can also read and write the blueprints, but also take into account the current blueprint loading process 😄
